OUTPUT_DIR: ./outputs/tdw
DATA_ROOT: [
  '/mnt/fs4/fanyun/human_stimulis/cloth_on_object',
  '/mnt/fs4/fanyun/human_stimulis/contain',
  '/mnt/fs4/fanyun/human_stimulis/slide_roll',
  '/mnt/fs4/fanyun/human_stimulis/collide2_new_0',
  '/mnt/fs4/fanyun/human_stimulis/collide2_new_1',
  '/mnt/fs4/fanyun/human_stimulis/unstable3_tower',
]
SOLVER:
  BASE_LR: 4.0e-4  # single GPU LR
  WEIGHT_DECAY: 1.0e-6
  SCHEDULER: 'cosine'
  MAX_ITERS: 2000000
  VAL_INTERVAL: 10000
  BATCH_SIZE: 10 # single GPU Batch Size
INPUT:
  IMAGE_MEAN: [173.443207494, 171.014595634, 165.733275512]
  IMAGE_STD: [39.172023998, 40.231433108, 42.64162651]
  TRAIN_NUM: 302587
  TRAIN_SLICE: [0, 1024, 1]
  VAL_NUM: 1048
  VAL_SLICE: [0, 1024, 32]
  BINARY_LABELS: ['is_colliding_dynamic']
  PRELOAD_TO_MEMORY: False
RPIN:
  BACKBONE: 'hourglass'
  ARCH: 'rpin'
  VE_FEAT_DIM: 256
  IN_FEAT_DIM: 256
  # prediction setting:
  INPUT_SIZE: 10
  CONS_SIZE: 1
  PRED_SIZE_TRAIN: 5
  PRED_SIZE_TEST: 5
  # input setting:
  INPUT_HEIGHT: 256
  INPUT_WIDTH: 256
  NUM_OBJS: 3
  # data augmentation
  HORIZONTAL_FLIP: True
  VERTICAL_FLIP: True
  # loss weight
  OFFSET_LOSS_WEIGHT: 100.0
  POSITION_LOSS_WEIGHT: 1.0
  # ----- image feature
  # IMAGE_UP: False
  # ROI_POOL_SIZE: 3
  # ----- coordinate feature
  COOR_FEATURE: True
  COOR_FEATURE_EMBEDDING: True
  # ----- conditional computation
  IN_CONDITION: True
  # ----- vae setting
  # VAE: True
  # VAE_KL_LOSS_WEIGHT: 3e-5
